version: '3'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: "jaeger"
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      # access jeager at http://localhost:16686

  zipkin:
    image: openzipkin/zipkin
    container_name: "zipkin"
    ports:
      - "9411:9411"
      # access zipkin at http://localhost:9411